BID='bid'
ASK='ask'
PRICE='price'
ON_TRADING='on_trading'
IS_LIMITUP='is_limitup'
IS_LIMITDOWN='is_limitdown'
DIRECTIONS=(ASK,BID)
STOCK_PRICING_DATA_KEY=(PRICE,ON_TRADING,IS_LIMITUP,IS_LIMITDOWN)
DATE_FMT='%Y-%m-%d'

